### PR TITLE
Session3 - Layering the Foundation

### PR DESCRIPTION
**Pull request by gavandivya**
nav
Creating a Header Component from Scratch using Function
Components with JSX

### CODE REVIEW

**Comment by gavandivya** [comment]
nav
Creating a Header Component from Scratch using Function Components with JSX

**Comment by nikitaj-57** [comment]
Reviewed.

**Comment by it-abhishek2000** [comment]
Really good and readable code

**Comment by it-abhishek2000** [comment]
reviewed

**Pull request merged**
